#!/bin/bash
if ! (which python3 >/dev/null && python3 --version | grep ' 3.' >/dev/null); then
  echo "You must have python 3 installed to run this."
  exit 1
fi

python3 $(dirname "$(readlink -f "$0")")/runme.py
